language: generic
sudo: required
services:
  - docker

before install:
  - docker build -t cheonu/docker-react-v1 -f Dockerfile.dev .

script:
  - docker run -e CI=true cheonu/docker-react-v1 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-898635122151"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
