language: generic
sudo: required
services:
  - docker

before install:
  - docker build -t cheonu/docker-react-v1 -f Dockerfile.dev .

script:
  - docker run -e CI=true cheonu/docker-react-v1 npm run test
